package com.example.inventoryinsight.navigation
const val ROUTE_SETTING = "setting"
const val ROUTE_HOME = "home"
const val ROUTE_ORDER = "order"
const val ROUTE_INVENTORY ="inventory"
const val ROUTE_LOGIN = "Login"
const val ROUTE_SIGNUP = "Signup"
const val ROUTE_UPDATE = "Update"
const val ROUTE_PAYMENT = "Payment"
const val ROUTE_ABOUT = "About"
const val ROUTE_STOCK = "Stock"
const val ROUTE_AUDIT = "Audit"
const val ROUTE_STOCKIN = "Stockin"
const val ROUTE_STOCKOUT = "Stockout"